---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helm-minio-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.min.io/
  timeout: 3m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.min.io/
  timeout: 3m
