# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: route53-env
    namespace: kube-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qkG7wBy2E0qDRRfo7nuvg751QSw=,iv:xnACK8NWNX/L5eq9f3qu3kRxWoKTc1HBPnUzssGdUEk=,tag:wUng+CMHu6pAcFiZwKDFMA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KTYvFTx7GGE2x5yF8mqKe+TbjYaHWQQlyMJN8ALcAvjp0G98OaQ1gw==,iv:n7hbZSMe6AKit3Q3iHICXVyiq0d9GArAPnewgZwD/Uw=,tag:aqLF3ugzQTR95RhR/oSRWw==,type:str]
    RECORDSET: ENC[AES256_GCM,data:J4EBuy++HaKkGDeu8v6rdjZf,iv:m6SlXHhPwDDN/dADWFjf+sBmbqdMy5LHiJ0N2r0Hbn8=,tag:s9M1/H6c19I6j/IMr/uNrg==,type:str]
    ZONEID: ENC[AES256_GCM,data:lEfzynnXwFaM3f79sII=,iv:aQB/Ea/TCnW3S3lmbijxzmWeaEDWJeWeDbCy+edQQcU=,tag:djvscQ9F1DuQVoHef2icKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-21T23:03:45Z"
    mac: ENC[AES256_GCM,data:NeKgyqTgf+uVM9ll7DqxCFiXE1mW0pn+icouysKgVlMeItBBLx0uXvJJ5SMZiiU0lf4H0xN48UY2pe1wj7E6vJjMAj+CuwtkxcSJ6OE7OVgEOe6DjcjAXEDKg7jltY3QowiaQyaTycGaIN7irpREs/u7UtuqBSKDIWg+JtRVqfc=,iv:+/bnyjkO0NR8ZusyYVlh0RATjYZXgk9TUPkkmhG+Hc0=,tag:WdOIVMydu49p239Z2RXR5A==,type:str]
    pgp:
        - created_at: "2021-08-21T23:03:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/5AT+wwHP9Agd/ZN+n26hW93aEfrt/DG94L9A1P4urB+fq
            Ov5Ri1Cgzd0a4vPNuIJP3WQOkp5YewYC6tkQKm3YzhsAR5UVh80n1DyfS5hSh2LF
            AT2iqMRMWttREoERnrxLAHr/Lm76w33kW3cydpUFcW8gZsh2w2tlz8DEIe2QLhKo
            ILflFYmNNQtt/ieHEIQlwczF+Pb9NXmU8AOXOv/ndrSsJAVKMtBr+DLamYC9gnWv
            M81EaqNCDGQU1+mfxIEkexnoQ51laJvGn2lusMS7yJWTF+0zggdbBc23ppduGiE3
            cDCe12nl0hU+m7WVcvW/AGTzCLYRAdilW6I7Kplg91g4YovQyLpUQzfUpylbnJSU
            3h3LzOCLF3+KUIA64NuSIgUS59jQmq3WeqHhvYf1T252PQiSP6slk3bJck8AMBBD
            m/MwXGKDC+BW4xv0usFKRQ+SHv4Tcw6KQDsrSRkt/tn2YBALegYuU7ZEP3ZSbmLj
            D7OQ6mzILyoojYn9xipHN51XvretuIZJw3jz45PacWzkdM6eNdCu3RQcHVAS0/ej
            0t90x/vrG7DFPVtltzeNUjBU4Ot06QlWVWAiWk/z9gplJtvrfkyu16ftJp0v7hGG
            LPuDboSbe5bn8S3ZW3u/vkUP/uY4ehjeDWmGZzrTQzzC80uN+hmOeu4IiON72Q7S
            XAEkiH8pfog5Oi4BGep/JVFHud9RDjtxGl1SvXOnoGnJcrtEWpJomIqhGCquzhfm
            2JlgQ5BC6BGtvAzWce3nBFNsTl+aDThCUmAXq2hR+NNpvm+OVQ4The25idJs
            =Rov3
            -----END PGP MESSAGE-----
          fp: B738248A67073DCE9E761E389DB6852043CF2CC7
        - created_at: "2021-08-21T23:03:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA39aiX8PMwmBARAAPo0DjcPNZyrsZV568csC8PB+zsdi/L9fGDko1l99ruva
            lVonvGjvH72/XP32eiDH8AgEqIyMUP+nSBAx5qmIGPxvOe5hIlyaqzcjhm9O0nRL
            640Ele4f8fc7zIhZkH/reomrp1x12KYrHLN794jFbSXn7k7fiUuYfJKrXzyidpW6
            83DUA+XdSNiI7x3HneM+1XDmVCTkGjq6wjjQSwNBvWPBRtNFnEGbIXjaaj98cH91
            qUBBY4hIAjIw+2EcIWHJzgrYdMMYiaeJkaKxO9ZbSIXem/YnNtSvgCWB11o5jI4h
            BMvAgNBBQw2BBQRwJRomeCC3xuD+mqN3gLQwDX7FMsRr1zb49qMACbnaLim9vMWX
            cDi5HS1BfuRyOcEiqL/fFmzYIEMqZPN/G7ggKzMASurBglzz+VhPx0sAwI1+t7Or
            G2I//2qGAX0gaXFTb6xbsHtuEfQkOpQNykfI6tm358qjxo1E9WLm968dJjEu19GV
            GFYsWb0bc1gj9uMYcXDERYr6+iBhUT9MXc93wsPQtTtLovBFD43MIOEBINDt0nRb
            cKG6TFy756WDcgSSgUdJzpIDOM7/3xDDlDIQzi8dOoJrJvNAuPXFTgudPl1fdkCU
            RMH8Br030zF7/GaYLgFZ2xq/GpooVkA1O5bYCiNXBm9bjOxlYz+QwZZ4rgpR9iPS
            5gG1WkFIixgIZKEHztdM+dnx5zsnGnVWWUoHfoggJsim9IVxkZlaJM08i0VEXkgt
            7tf8h5Ou5iWKzVBId+Atb63k8Q3KE6ihyo6UwWrRNEMbVOLu4h/XAA==
            =MYEy
            -----END PGP MESSAGE-----
          fp: 21E16B8D2EE875306A6C9968D83077B99F8C6643
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
