---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: default
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: monica
      tag: 3.2.0-apache
    env:
      APP_URL: "https://monica.${SECRET_DOMAIN}"
      APP_ENV: production
      DB_HOST: monica-mariadb
      DB_DATABASE: monica
      DB_USERNAME: monica
      DEFAULT_MAX_STORAGE_SIZE: 4096
    ingress:
      main: 
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
          hajimari.io/enable: "true"
          hajimari.io/icon: "card-account-phone"
          hajimari.io/instance: "external"
        hosts:
        - host: "monica.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "monica.${SECRET_DOMAIN}"
          secretName: monica-cert-external
    persistence:
      config:
        enabled: true
        existingClaim: monica-config
    podAnnotations:
      backup.velero.io/backup-volumes: config
    tolerations:
    - key: "arm"
      operator: "Exists"
    mariadb:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: 10.5.9-debian-10-r46
      primary:
        persistence:
          enabled: true
          existingClaim: monica-mariadb-data
      auth:
        database: monica
        username: monica
  valuesFrom:
  - kind: Secret
    name: "monica-helm-values"
    optional: false
