---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: default
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: monica
      tag: 3.1.3-apache
    env:
      APP_URL: https://monica.homelab.tokyo
      APP_ENV: production
      DB_HOST: monica-mariadb
      DB_DATABASE: monica
      DB_USERNAME: monica
      DEFAULT_MAX_STORAGE_SIZE: 4096
    ingress:
      main: 
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx-external"
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/auth-signin: https://auth.homelab.tokyo
          nginx.ingress.kubernetes.io/auth-url: https://auth.homelab.tokyo/api/verify
          hajimari.io/enable: "true"
          hajimari.io/icon: "card-account-phone"
        hosts:
        - host: "monica.homelab.tokyo"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "monica.homelab.tokyo"
          secretName: monica-cert-external
    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        size: 2Gi
    tolerations:
    - key: "arm"
      operator: "Exists"
    mariadb:
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/mariadb
        tag: 10.5.9-debian-10-r46
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
      auth:
        database: monica
        username: monica
  valuesFrom:
  - kind: Secret
    name: "monica-helm-values"
    optional: false
