---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari-internal
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://toboshii.github.io/hajimari
      chart: hajimari
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    env:
      TZ: "America/Chicago"
    hajimari:
      title: Hajimari (Internal)
      name: "Winston"
      instanceName: "internal"
      namespaceSelector:
        matchNames:
          - default
          - media
          - monitoring
          - longhorn-system
      customApps: 
        - name: "Monica"
          url: "https://monica.${SECRET_DOMAIN}"
          icon: "card-account-phone"
      groups:
        - name: Media
          links:
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
    podSecurityContext:
      fsGroup: 101
    resources:
      requests:
        cpu: 100m
        memory: 128M
