---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onedrive
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: onedrive
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: wrmilling-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      ONEDRIVE_DOWNLOADONLY: 1
    persistence:
      config:
        storageClass: "rook-ceph-block"
        size: 1Gi
      data:
        storageClass: "rook-ceph-block"
        size: 1Gi