---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultDataPath: /longhorn
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      taintToleration: arm=true:NoExecute
      backupTarget: nfs://10.10.10.31:/mnt/tardisk/k3s
    ingress:
      enabled: true
      host: "longhorn.k.${SECRET_DOMAIN}"
      tlsSecret: longhorn-cert
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # nginx.ingress.kubernetes.io/auth-signin: "https://auth.${SECRET_DOMAIN}"
        # nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/api/verify"
        hajimari.io/enable: "true"
        hajimari.io/icon: "harddisk"
        hajimari.io/instance: "internal"
        hajimari.io/appName: "Longhorn"
        hajimari.io/group: "Cluster Ops"
