---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.min.io/
      chart: minio
      version: 3.1.3
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-09-09T21-37-07Z
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2021-09-02T09-21-27Z
    tolerations:
      - key: "arm"
        operator: "Exists"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: ["minio.k.${SECRET_DOMAIN}"]
      tls:
        - hosts:
            - "minio.k.${SECRET_DOMAIN}"
          secretName: minio-cert
    persistence:
      existingClaim: "nfs-minio-pvc"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    gateway:
      type: "nas"
      replicas: 3
    metrics:
      serviceMonitor:
        enabled: true
    securityContext:
      enabled: false
  valuesFrom:
  - kind: Secret
    name: "minio-helm-values"
    optional: false
