---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.min.io/
      chart: minio
      version: 8.0.10
      sourceRef:
        kind: HelmRepository
        name: helm-minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-10-08T23-58-24Z
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2021-09-23T05-44-03Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    accessKey: ${SECRET_MINIO_ACCESS_KEY}
    secretKey: ${SECRET_MINIO_SECRET_KEY}
    persistence:
      existingClaim: "nfs-minio-pvc"
    ingress:
      enabled: false
    tolerations:
      - key: "arm"
        operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 3
