---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.min.io/
      chart: minio
      version: 8.0.10
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2020-08-08T04-50-06Z
    mcImage:
      repository: jessestuart/mc
      tag: RELEASE.2020-08-08T02-33-58Z
    helmKubectlJqImage:
      repository: drnic/kubectl
      tag: 1.16
    persistence:
      existingClaim: "nfs-minio-pvc"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx-internal
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: ["minio.k.${SECRET_DOMAIN}"]
      tls:
        - hosts:
            - "minio.k.${SECRET_DOMAIN}"
          secretName: minio-cert
    tolerations:
      - key: "arm"
        operator: "Exists"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    securityContext:
      enabled: false
    metrics:
      serviceMonitor:
        enabled: true
    nasgateway:
      enabled: true
      # Number of parallel instances
      replicas: 3
  valuesFrom:
    - kind: Secret
      name: "minio-helm-values"
      optional: false
