name: renovate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  helm-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install yq
      run: |
        sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq

    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1
      with:
        cluster-path: "./"

    - name: Create pull request for HelmRelease annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: helm-release-annotations
        delete-branch: true
        title: "[renovate] create helmrelease annotations [ci-skip]"
        signoff: true
        committer: "Winston R. Milling <wrmilling@users.noreply.github.com>"
        author: "Winston R. Milling <wrmilling@users.noreply.github.com>"
        assignees: "wrmilling"
        commit-message: Create renovatebot helmrelease annotations
        body: |
          Signed-off-by: Winston R. Milling <WRMilling@users.noreply.github.com>
        labels: renovate/helm-release-annotations
